### ISSUE TITLE
Build fails for target armv7-linux-androideabi

### ISSUE THREAD

**Issue by jlewallen** [CarlKCarlK/range-set-blaze#2]
Hello there!

I recently tried to build a project of mine for Android that uses your wonderful library and encountered a few different categories of error:

```rust
error[E0437]: type `Output` is not a member of trait `Integer`
 --> src/integer.rs:9:5
  |
9 |     type Output = usize;
  |     ^^^^^^^^^^^^^^^^^^^^ not a member of trait `Integer`
```

Several of these for the various integer widths and then the following:

```rust
error[E0277]: the trait bound `i128: OverflowingSub` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `OverflowingSub` is not implemented for `i128`
    |
    = help: the following other types implement trait `OverflowingSub`:
              i16
              i32
              i64
              i8
              isize
              u16
              u32
              u64
            and 2 others
note: required by a bound in `Integer`
   --> src/lib.rs:58:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
58  |     + OverflowingSub
    |       ^^^^^^^^^^^^^^ required by this bound in `Integer`

error[E0277]: the trait bound `i128: NumCast` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `NumCast` is not implemented for `i128`
    |
    = help: the following other types implement trait `NumCast`:
              f32
              f64
              i16
              i32
              i64
              i8
              isize
              u16
            and 4 others
note: required by a bound in `Integer`
   --> src/lib.rs:55:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
55  |     + num_traits::NumCast
    |       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Integer`

rror[E0277]: the trait bound `i128: Bounded` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `Bounded` is not implemented for `i128`
    |
    = help: the following other types implement trait `Bounded`:
              f32
              f64
              i16
              i32
              i64
              i8
              isize
              u16
            and 4 others
note: required by a bound in `Integer`
   --> src/lib.rs:54:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
54  |     + num_traits::Bounded
    |       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Integer`

```

I also get the above for the `u128` implementation of `Integer`.

I'm new to rust myself and could use some pointers chasing down the appropriate solutions for this. The first set of errors go away if you omit the associated type completely (via commenting is what I tried), but that doesn't affect the others and I'm not sure of the consequences of that. My plan had been to refine the `#[cfg(...)]` around them. As far as the others I think I'm at the "needs to know the root cause of the discrepancies" phase and that's not clear to me as a novice.

Steps to reproduce:

```
rustup target add armv7-linux-androideabi
cargo build --target armv7-linux-androideabi
```

Thanks!

**Comment by CarlKCarlK** [comment]
Jacob, Thanks for trying the crate and finding this problem. I'm traveling for the next week but will look in to it soon after I get back.
Carl
________________________________
From: Jacob Lewallen ***@***.***>
Sent: Wednesday, May 10, 2023 7:44:37 PM
To: CarlKCarlK/range-set-blaze ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CarlKCarlK/range-set-blaze] Build fails for target armv7-linux-androideabi (Issue #2)


Hello there!

I recently tried to build a project of mine for Android that uses your wonderful library and encountered a few different categories of error:

error[E0437]: type `Output` is not a member of trait `Integer`
 --> src/integer.rs:9:5
  |
9 |     type Output = usize;
  |     ^^^^^^^^^^^^^^^^^^^^ not a member of trait `Integer`

Several of these for the various integer widths and then the following:

error[E0277]: the trait bound `i128: OverflowingSub` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `OverflowingSub` is not implemented for `i128`
    |
    = help: the following other types implement trait `OverflowingSub`:
              i16
              i32
              i64
              i8
              isize
              u16
              u32
              u64
            and 2 others
note: required by a bound in `Integer`
   --> src/lib.rs:58:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
58  |     + OverflowingSub
    |       ^^^^^^^^^^^^^^ required by this bound in `Integer`

error[E0277]: the trait bound `i128: NumCast` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `NumCast` is not implemented for `i128`
    |
    = help: the following other types implement trait `NumCast`:
              f32
              f64
              i16
              i32
              i64
              i8
              isize
              u16
            and 4 others
note: required by a bound in `Integer`
   --> src/lib.rs:55:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
55  |     + num_traits::NumCast
    |       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Integer`

rror[E0277]: the trait bound `i128: Bounded` is not satisfied
   --> src/integer.rs:154:18
    |
154 | impl Integer for i128 {
    |                  ^^^^ the trait `Bounded` is not implemented for `i128`
    |
    = help: the following other types implement trait `Bounded`:
              f32
              f64
              i16
              i32
              i64
              i8
              isize
              u16
            and 4 others
note: required by a bound in `Integer`
   --> src/lib.rs:54:7
    |
45  | pub trait Integer:
    |           ------- required by a bound in this trait
...
54  |     + num_traits::Bounded
    |       ^^^^^^^^^^^^^^^^^^^ required by this bound in `Integer`

I also get the above for the u128 implementation of Integer.

I'm new to rust myself and could use some pointers chasing down the appropriate solutions for this. The first set of errors go away if you omit the associated type completely (via commenting is what I tried), but that doesn't affect the others and I'm not sure of the consequences of that. My plan had been to refine the #[cfg(...)] around them. As far as the others I think I'm at the "needs to know the root cause of the discrepancies" phase and that's not clear to me as a novice.

Steps to reproduce:

rustup target add armv7-linux-androideabi
cargo build --target armv7-linux-androideabi


Thanks!

**Comment by crioux** [comment]
Encountering the same issue on wasm32-unknown-unknown

**Comment by crioux** [comment]
PR added to fix this: https://github.com/CarlKCarlK/range-set-blaze/pull/3

**Comment by CarlKCarlK** [comment]
I've started working on this. I'm thinking of also removing support for 16-bit because I can't see how to test it. (Also, if anyone needs it, it would not be hard to add using 32-bit as an example.).

What do you think about dropping support for 16-bit?

**Comment by jlewallen** [comment]
No objections here. I came across the original issue building a project that uses https://github.com/fzyzcjy/flutter_rust_bridge, and can't imagine there are any platforms/architectures that would make sense for that that are 16-bit. I'm guessing that it would mostly affect projects targeting smaller MCUs.

**Comment by CarlKCarlK** [comment]
Thanks for finding this bug! It is fixed and I've added new 'github action' testing that checks 32-bit Linux and 32-bit Windows.
For now, 16-bit support is removed. If we ever find a way to test it, we can add it back in.

**Comment by jlewallen** [comment]
Thanks for the fix, and for the library Carl!
